---
## Ubuntu16.04: rmmod: ERROR: Module ipv6 is builtin.
- name: rmmodipv6
  command: rmmod ipv6
  ignore_errors: true

- name: modipv6
  command: modprobe ipv6
  ignore_errors: true

- name: restart network
  service: name=network state=restarted
